version: '3'
services:
  prepare:
    image: "adreeve/python-numpy:latest"
    working_dir: /data/prepare
    command: ["bash", "-c", "pip install easydict pyopenssl && python -u install.py"]
    volumes:
      - ./DataSets:/data/DataSets
      - ./Output:/data/Output
      - ./configs:/data/configs
      - ./PretrainedModels:/data/PretrainedModels
      - ./web:/data/web
      - ./prepare:/data/prepare
 
  predict-lb:
    image: "tutum/haproxy"
    links:
      - predict:predict
 
  predict:
    image: "starcaspar/rod:latest"
    command: ["bash", "-c", "source /root/anaconda3/bin/activate /root/anaconda3/envs/cntk-py35 && python -u score.py"]
    devices:
      - /dev/nvidia0
    volumes:
      - ./DataSets:/cntk/Examples/Image/DataSets
      - ./Output:/cntk/Examples/Image/Detection/FasterRCNN/Output
      - ./configs:/cntk/Examples/Image/Detection/utils/configs
    expose:
      - 8002

  train:
    image: "starcaspar/rod:latest"
    command: ["bash", "-c", "source /root/anaconda3/bin/activate /root/anaconda3/envs/cntk-py35 && python -u train.py"]
    devices:
      - /dev/nvidia0
    volumes:
      - ./DataSets:/cntk/Examples/Image/DataSets
      - ./Output:/cntk/Examples/Image/Detection/FasterRCNN/Output
      - ./configs:/cntk/Examples/Image/Detection/utils/configs
      - ./PretrainedModels:/cntk/PretrainedModels

  web-lb:
    image: "node:8"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./web:/home/node/app
    ports:
      - "443:3000"
    command: ["bash", "-c", "npm install && npm start"]
    links:
      - predict:predict_lb

  web:
    image: "node:8"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./web:/home/node/app
    ports:
      - "443:3000"
    command: ["bash", "-c", "npm install && npm start"]
    links:
      - predict

  
