services:
  predict:
    command:
    - bash
    - -c
    - source /root/anaconda3/bin/activate /root/anaconda3/envs/cntk-py35 && python
      -u score.py
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: starcaspar/rod:latest
    volumes:
    - ./DataSets:/cntk/Examples/Image/DataSets
    - ./Output:/cntk/Examples/Image/Detection/FasterRCNN/Output
    - ./configs:/cntk/Examples/Image/Detection/utils/configs
    - nvidia_driver_384.111:/usr/local/nvidia:ro
  prepare:
    command:
    - bash
    - -c
    - pip install easydict pyopenssl && python -u /data/prepare/install.py
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: adreeve/python-numpy:latest
    volumes:
    - ./DataSets:/data/DataSets
    - ./Output:/data/Output
    - ./configs:/data/configs
    - ./PretrainedModels:/data/PretrainedModels
    - ./web:/data/web
    - ./prepare:/data/prepare
    - nvidia_driver_384.111:/usr/local/nvidia:ro
  train:
    command:
    - bash
    - -c
    - source /root/anaconda3/bin/activate /root/anaconda3/envs/cntk-py35 && python
      -u train.py
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: starcaspar/rod:latest
    volumes:
    - ./DataSets:/cntk/Examples/Image/DataSets
    - ./Output:/cntk/Examples/Image/Detection/FasterRCNN/Output
    - ./configs:/cntk/Examples/Image/Detection/utils/configs
    - ./PretrainedModels:/cntk/PretrainedModels
    - nvidia_driver_384.111:/usr/local/nvidia:ro
  web:
    command: npm start
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    environment:
    - NODE_ENV=production
    image: node:8
    links:
    - predict
    ports:
    - 443:3000
    user: node
    volumes:
    - ./web:/home/node/app
    - nvidia_driver_384.111:/usr/local/nvidia:ro
    working_dir: /home/node/app
version: '3'
volumes:
  nvidia_driver_384.111:
    external: true
